### ISSUE TITLE
Pull credentials from environment variables

### ISSUE THREAD

**Issue by cyclotron3k** [erniebrodeur/pushover#37]
I think it would be pretty cool if the Pushover gem tried to pull the app token and user key from environment variables (if they haven't already been explicitly provided).

This way, if you're using the Pushover gem or binary, you only have to ensure the credentials are available as environment variables and then you don't have to bother passing credentials around, accidentally checking them into source control, or getting them into your bash history, etc, etc.

I'm happy to make a PR if you're interested in implementing this feature?

**Comment by erniebrodeur** [comment]
You can't really use pushover from the commandline without some sort of shell wrapper or script.

In /bin/sh you can just use substitution, in the form of:

    API_KEY=1 TOKEN=2 pushover --api-key=$API_KEY --token=$TOKEN 

and the shell will do shell word replacement to have the same effect of not pushing credentials around (which is valid).

If you are using it inside of a ruby gem as a library, nothing stops you from referencing ENV['API_KEY'] and ENV['TOKEN'] inside your ruby code.

I've had this very feature in the past in the application, but I question it's value vs having more code to maintain and load up.

the Pushover gem as it stands right now is very thin, using only Excon to do the heavy lifting (and I might revert to just using Net:HTTP so I can go with near zero dependencies).  

Is there some reason the above solution doesn't work?   Otherwise this feels like redundant code.

Sorry.

**Comment by cyclotron3k** [comment]
In containerised environments, passing credentials around via environment variables is quite common. I think that's why Gems like the GCP and AWS libraries make use of environment variables in this way. I also find it's useful for cronjobs too, but that's just me.

Anyway, as you say, there's already a perfectly good work-around, so your call. No hard feelings!
